import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from dotenv import load_dotenv
from datetime import datetime, timedelta

from config import REPORT_DIR, TIME_WINDOW_DAYS

load_dotenv()

report_dir = REPORT_DIR
time_window_days = TIME_WINDOW_DAYS
SENDER = os.getenv("EMAIL_SENDER")
PASSWORD = os.getenv("EMAIL_PASSWORD")
RECEIVER = os.getenv("EMAIL_RECEIVER")
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))


def get_latest_report():
    if not os.path.exists(report_dir):
        return None
        
    # get all files
    files = [os.path.join(report_dir, f) for f in os.listdir(report_dir) 
             if f.endswith(".pdf")]
    
    if not files:
        return None
        
    # sort by modification time, get the latest one
    latest_file_path = max(files, key=os.path.getmtime)

    #check if the latest file is within the time window (else it was sent before)
    file_mtime = datetime.fromtimestamp(os.path.getmtime(latest_file_path))
    now = datetime.now()
    threshold = now - timedelta(days=time_window_days + 1)
    
    if file_mtime < threshold:
        print(f"Latest report is too old (modified at {file_mtime}), skipping email")
        return None
    
    return latest_file_path

def send_email():
    if not SENDER or not PASSWORD or not RECEIVER:
        print("Email sender, password, or receiver is not set")
        return
    
    attachment_path = get_latest_report()

    if not attachment_path:
        print("no new report found")
    
    # create email message
    msg = MIMEMultipart()
    msg['From'] = SENDER
    msg['To'] = RECEIVER
    msg['Subject'] = f"Weekly Research Report - {datetime.today().strftime('%Y-%m-%d')}"
    
    if attachment_path:
        filename = os.path.basename(attachment_path)
        
        body_text = f"""
        Hi,
        
        Here is your weekly AI research report generated by your Agent.
        
        Attached file: {filename}
        
        Best,
        Your AI Assistant
        """
        msg.attach(MIMEText(body_text, 'plain'))
        
        # attach the PDF file
        try:
            with open(attachment_path, "rb") as f:
                part = MIMEApplication(f.read(), Name=filename)
        
            part['Content-Disposition'] = f'attachment; filename="{filename}"'
            msg.attach(part)
        except Exception as e:
            print(f"Failed to read attachment: {e}")
            msg.attach(MIMEText(f"Failed to read attachment: {e}", 'plain'))
        
    
    else:
        body_text =f"""
        Hi,

        No new reports for this week. Have a leisure week!
        
        Best,
        Your AI Assistant"""

        msg.attach(MIMEText(body_text, 'plain'))
    
    # connect to SMTP server and send email
    try:
        print(f"Connecting to SMTP server ({SMTP_SERVER})...")
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls() 
            server.login(SENDER, PASSWORD)
            server.send_message(msg)
            
        print(f"Email sent successfully to {RECEIVER}")
        
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    send_email()